config/routes.rb
GCIReviews::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :account do
    resources :gci_reviews_apis
    resources :gci_reviews_api_color_schemes
  end

  root 'static_pages#index'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'sign-in' => 'session#new', as: 'sign_in'
  post 'sign-in' => 'session#create', as: 'sign_in_create'
  delete 'sign-out' => 'session#destroy', as: 'sign_out'
  get 'sign-up' => 'static_pages#sign_up', as: 'sign_up'
  post 'sign-up' => 'static_pages#sign_up_create', as: 'sign_up_create'

  get 'account' => 'session#index'

  get 'reviews/:api' => 'gci_reviews#load', :defaults => { :format => :js }, as: 'gci_reviews'
  get 'reviews/:api/box' => 'gci_reviews#box', :defaults => { :format => :html }, as: 'gci_reviews_box'
  get 'reviews/:api/list' => 'gci_reviews#list', :defaults => { :format => :json }, as: 'gci_reviews_list'
  post 'reviews/:api/new' => 'gci_reviews#new', :defaults => { :format => :json }, as: 'gci_reviews_new'
  match 'reviews/:api/new', to: 'gci_reviews#set_options', via: :options

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def sign_up
    @user = User.new
  end

  def sign_up_create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        format.html {
          sign_in @user
          flash[:success] = 'Welcome to the Global Clinic Index!'
          redirect_to account_url
        }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'sign_up' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>Global Clinic Index or <b>GCI</b> is the world's first rating for clinics. We use various metrics and the rating is
  made out of more than 1.000.000 reviews. We index every clinic on the earth.</p>

app/views/static_pages/contact.html.erb
<% provide :title, 'Contact' %>
<h1>Contact</h1>
<p>Feel free to visit our home page at <a href="http://medbeaver.com">MedBeaver.com</a> or write us an e-mail at
  <a href="mailto:gci@medbeaver.com">gci@medbeaver.com</a>.</p>

app/views/static_pages/index.html.erb
<div class="jumbotron home-jumbotron" style="background-image: url('<%= image_path 'happy-people.jpg' %>');">
  <h1>Global clinic index</h1>

  <p>Get in touch with world's first clinic benchmarking. Place the review to your page and get higher rank!</p>

  <p><%= link_to "Learn more", "/about", class: "btn btn-primary btn-lg", role: "button" %>

</div>

<div class="row">
  <div class="col-md-4">
    <h2>Heading</h2>

    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
      condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec
      sed odio dui. </p>

    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
  </div>
  <div class="col-md-4">
    <h2>Heading</h2>

    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
      condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec
      sed odio dui. </p>

    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
  </div>
  <div class="col-md-4">
    <h2>Heading</h2>

    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis
      euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo
      sit amet risus.</p>

    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
  </div>
</div>

app/views/static_pages/sign_up.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= bootstrap_form_for @user, :url => sign_up_create_path, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-4" do |f| %>
        <%= f.text_field :firstname, label: "First name" %>
        <%= f.text_field :lastname, label: "Last name" %>
        <%= f.email_field :email, label: "E-mail" %>
        <%= f.password_field :password, label: "Password" %>
        <%= f.password_field :password_confirmation, label: "Confirmation" %>
        <%= f.form_group do %>
            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    <% end %>
  </div>
</div>