config/routes.rb
GCIReviews::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :account do
    resources :gci_reviews_apis
    resources :gci_reviews_api_color_schemes
  end

  root 'static_pages#index'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'sign-in' => 'session#new', as: 'sign_in'
  post 'sign-in' => 'session#create', as: 'sign_in_create'
  delete 'sign-out' => 'session#destroy', as: 'sign_out'
  get 'sign-up' => 'static_pages#sign_up', as: 'sign_up'
  post 'sign-up' => 'static_pages#sign_up_create', as: 'sign_up_create'

  get 'account' => 'session#index'

  get 'reviews/:api' => 'gci_reviews#load', :defaults => { :format => :js }, as: 'gci_reviews'
  get 'reviews/:api/box' => 'gci_reviews#box', :defaults => { :format => :html }, as: 'gci_reviews_box'
  get 'reviews/:api/list' => 'gci_reviews#list', :defaults => { :format => :json }, as: 'gci_reviews_list'
  post 'reviews/:api/new' => 'gci_reviews#new', :defaults => { :format => :json }, as: 'gci_reviews_new'
  match 'reviews/:api/new', to: 'gci_reviews#set_options', via: :options

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :signed_in_user, except: [:new, :create]

  def index
    @clinic = current_user.clinic
  end

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to account_url
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  private
  def signed_in_user
    redirect_to sign_in_url, notice: "Please sign in." unless online?
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    remember_token                     = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user  ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def online?
    !current_user.nil?
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/views/session/index.html.erb
<% provide :title, 'My account' %>
<h1>Welcome <b><%= current_user.full_name %></b></h1>

<% if @clinic != nil %>
    <p class="lead">You have assigned clinic: <b><%= @clinic.name %></b>.</p>

    <% if @clinic.gci_reviews_apis.any? %>
        <p>Congratulation. You have <b><%= pluralize @clinic.gci_reviews_apis.count, 'gci reviews box' %></b> assigned
          to your account. <%= link_to "Go to the Reviews API section", account_gci_reviews_apis_path %> to manage all
          reviews. </p>
        <div style="margin: 10px 0;">
          <%= link_to 'Manage GCI Reviews Boxes', account_gci_reviews_apis_path, class: 'btn btn-primary' %>
        </div>
        <div>
          <%= link_to 'Manage Color Schemes', account_gci_reviews_api_color_schemes_path, class: 'btn btn-primary' %>
        </div>
    <% else %>
        <p>You don't have any
          <b>GCI Reviews API created</b>. <%= link_to "Create GCI Reviews API", new_account_gci_reviews_api_path %> to
          easily add
          reviews to your website.</p>
    <% end %>
<% else %>
    <p class="lead">There is no clinic assigned to you. <%= link_to "Contact us", contact_path %> if you own any clinic
      and we will assign it to you.</p>
<% end %>

app/views/session/new.html.erb
<% provide(:title, "Sign in") %>
<h1>Sign in</h1>
<%= bootstrap_form_for :session, url: sign_in_create_path, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-4" do |f| %>
    <%= f.text_field :email, label: "E-mail" %>
    <%= f.password_field :password %>
    <%= f.form_group do %>
        <%= f.primary "Sign in", class: "btn-lg" %>
    <% end %>
<% end %>