config/routes.rb
GCIReviews::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :account do
    resources :gci_reviews_apis
    resources :gci_reviews_api_color_schemes
  end

  root 'static_pages#index'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'sign-in' => 'session#new', as: 'sign_in'
  post 'sign-in' => 'session#create', as: 'sign_in_create'
  delete 'sign-out' => 'session#destroy', as: 'sign_out'
  get 'sign-up' => 'static_pages#sign_up', as: 'sign_up'
  post 'sign-up' => 'static_pages#sign_up_create', as: 'sign_up_create'

  get 'account' => 'session#index'

  get 'reviews/:api' => 'gci_reviews#load', :defaults => { :format => :js }, as: 'gci_reviews'
  get 'reviews/:api/box' => 'gci_reviews#box', :defaults => { :format => :html }, as: 'gci_reviews_box'
  get 'reviews/:api/list' => 'gci_reviews#list', :defaults => { :format => :json }, as: 'gci_reviews_list'
  post 'reviews/:api/new' => 'gci_reviews#new', :defaults => { :format => :json }, as: 'gci_reviews_new'
  match 'reviews/:api/new', to: 'gci_reviews#set_options', via: :options

end

app/controllers/gci_reviews_controller.rb
class GciReviewsController < ApplicationController
  before_action :must_have_api_code
  before_action :check_valid_url, only: [:box, :list, :load, :new]
  skip_before_filter :verify_authenticity_token

  # Loading initial javascript, css
  def load
    respond_to do |format|
      format.js { render :action => 'load_reviews' }
      format.css { render :action => 'full_box' }
    end
  end

  # Loading HTML box for review
  def box
    respond_to do |format|
      format.html {
        @clinic = @gci_reviews_api.clinic

        if @gci_reviews_api.gci_reviews_api_type.show_type == 'full'
          render action: 'full_box', layout: false
        else
          render action: 'mini_box', layout: false
        end
      }
    end

  end

# Json ajax queries for reviews
  def list
    respond_to do |format|
      format.json {
        sort_hash = { '1' => 'created_at DESC', '2' => 'created_at ASC', '3' => 'overall_satisfaction_score DESC, created_at DESC', '4' => 'overall_satisfaction_score ASC, created_at DESC' }

        page         = params[:page] || 1
        sort         = sort_hash[params[:sort]] || sort_hash['1']
        max_per_page = @gci_reviews_api.reviews_per_page
        total_pages  = (@gci_reviews_api.gci_reviews_api_reviews.count / max_per_page).ceil
        show_from    = (page.to_i - 1)*max_per_page;
        show_to = page.to_i*max_per_page;

        list_of_reviews = @gci_reviews_api.gci_reviews_api_reviews.where(approved: true).order(sort).offset(show_from).limit(max_per_page).collect do |item|
          item.as_json(include: :country)
        end

        render json: { list: list_of_reviews, count: total_pages, page: page, showing_from: show_from + 1, showing_to: show_to }
      }
    end
  end

  # Adding new review
  def new
    respond_to do |format|
      format.json {
        response = { status: 'ok' }
        render json: response.to_json
      }
    end
  end

  # Options header is sent before POST. This is needed for AJAX Review insert
  def set_options
    response.headers['Access-Control-Allow-Origin']  = '*'
    response.headers["Access-Control-Allow-Headers"] = "Content-Type, X-Requested-With"
    response.headers["Access-Control-Allow-Methods"] = "GET, PUT, POST, DELETE"
    render nothing: true, status: 204
  end

  private
  def must_have_api_code
    @gci_reviews_api = GciReviewsApi.find_by(api_code: params.require(:api))
  end

  # Check for correct referer - compare only domain name
  def check_valid_url
    refererURI                                  = URI(request.referer.to_s).host.to_s
    allowedURI                                  = @gci_reviews_api.web_page.to_s.split(',').map! { |uri| uri = URI(uri).host }

    # Allow all url
    headers['Access-Control-Allow-Origin']      = '*'
    headers['Access-Control-Request-Method']    = '*'
    headers['Access-Control-Allow-Headers']     = '*'
    headers['Access-Control-Allow-Credentials'] = "true"

    respond_to do |format|
      format.all {
        render text: 'Access denied. Check your settings.'.html_safe, layout: false
      }
      #end if refererURI.empty? || !allowedURI.include?(refererURI)
    end if false
  end
end

app/helpers/gci_reviews_helper.rb
module GciReviewsHelper
end

app/views/gci_reviews/_form_stars.html.erb
<div class="gci-reviews-api-full-box-details-reviews-form-score-stars">
  <input type="hidden" name="<%= name %>" value="-1">

  <% 10.times do %><img src="<%= image_url 'star_off_medium.png' %>"><% end %>
</div>

app/views/gci_reviews/_review_tempo.html.erb
<div class="gci-reviews-api-full-box-reviews-all-reviews">
  <div data-template class="gci-reviews-api-full-box-reviews-all-item">
    <div class="gci-reviews-api-full-box-reviews-all-item-details">
      <div class="gci-reviews-api-full-box-reviews-all-item-details-name">
        {{name}}
      </div>
      <div class="gci-reviews-api-full-box-reviews-all-item-details-country">
        {{city}}, {{country.label}}
      </div>
      <div class="gci-reviews-api-full-box-reviews-all-item-details-date">
        {{created_at | date 'MMMM D, YYYY'}}
      </div>
      <div class="gci-reviews-api-full-box-reviews-all-item-details-rating">
        <span class="gci-reviews-rating-medium">
          <span style="width: {{overall_satisfaction_score_width}}px;">

          </span>
        </span>
        <b>{{overall_satisfaction_score}}</b>
      </div>
      <div class="gci-reviews-api-full-box-reviews-all-item-details-final-rating">
        <b>Final rating:</b> I recommend this facility.
      </div>
    </div>
    <div class="gci-reviews-api-full-box-reviews-all-item-text">
      <div class="gci-reviews-api-full-box-reviews-all-item-text-normal">{{normal_text}}</div>

      <div class="gci-reviews-api-full-box-reviews-all-item-text-positive">{{positive_text}}</div>

      <div class="gci-reviews-api-full-box-reviews-all-item-text-negative">{{negative_text}}</div>
    </div>
  </div>
</div>

app/views/gci_reviews/_stars.html.erb
<span class="gci-reviews-rating-medium">
  <span style="width: <%= get/base * 105%>px;"></span>
</span>

app/views/gci_reviews/full_box.css.erb
.gci-reviews-api-full-box {
    font-size: 14px;
    margin-bottom: 20px;
}

.gci-reviews-api-full-box h1 {
    color: #206083;
}

.gci-reviews-api-full-box-details {
    position: relative;
    margin-bottom: 10px;
    width: 100%;
    display: table;
}

.gci-reviews-api-full-box-gcr-box {
    width: 190px;
    border: 1px solid #206083;
    display: table-cell;
    vertical-align: top;
}

.gci-reviews-api-full-box-gcr-box-title {
    background-color: #206083;
    color: #FFFFFF;
    padding: 5px 10px;
}

.gci-reviews-api-full-box-gcr-box-title-gcr {
    font-weight: bold;
}

.gci-reviews-api-full-box-gcr-box-title-global-clinic-rating {
    font-size: 10px;
}

.gci-reviews-api-full-box-gcr-box-content {
    padding: 15px 10px;
    text-align: center;
    font-size: 11px;
    color: #206083;
}

.gci-reviews-api-full-box-gcr-box-content-score {
    font-weight: bold;
    font-size: 50px;
}

.gci-reviews-api-full-box-gcr-box-content-text {
}

/*--------------------REVIEWS DETAILS-----------------------*/
.gci-reviews-api-full-box-details-reviews-details {
    display: table-cell;
    vertical-align: top;
    padding-left: 30px;
}

.gci-reviews-api-full-box-details-reviews-details h2 {
    margin-top: 0;
    font-size: 16px;
    font-weight: bold;
    color: #206083;
}

.gci-reviews-api-full-box-details-reviews-details-reviews-count {
    margin-top: 10px;
    font-size: 12px;
}

.gci-reviews-api-full-box-details-reviews-details-table {
    display: table;
}

.gci-reviews-api-full-box-details-reviews-details-row {
    display: table-row;
}

.gci-reviews-api-full-box-details-reviews-details-label {
    display: table-cell;
}

.gci-reviews-api-full-box-details-reviews-details-stars {
    display: table-cell;
    padding-left: 20px;
}

/*--------------------WRITE REVIEW--------------------*/
.gci-reviews-api-full-box-details-reviews-write-review {
    position: absolute;
    bottom: 10px;
    right: 20px;

    display: inline-block;
    outline: none;
    cursor: pointer;
    text-align: center;
    text-decoration: none;
    font-weight: bold;
    text-shadow: 0 1px 1px rgba(0, 0, 0, 0.3);
    -webkit-border-radius: .5em;
    -moz-border-radius: .5em;
    border-radius: .5em;
    -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
    -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
    color: #FFFFFF;
    border: solid 1px #da7c0c;
    background: #f78d1d;
    background: -webkit-gradient(linear, left top, left bottom, from(#feba02), to(#f47a20));
    background: -moz-linear-gradient(top, #feba02, #f47a20);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#feba02', endColorstr='#f47a20');

    font-size: 18px;
    padding: 10px 20px;
}

.gci-reviews-api-full-box-details-reviews-write-review:hover {
    text-decoration: underline;
    background: #f47c20;
    background: -webkit-gradient(linear, left top, left bottom, from(#f88e11), to(#f06015));
    background: -moz-linear-gradient(top, #f88e11, #f06015);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#f88e11', endColorstr='#f06015');
    color: #FFFFFF;
}

/*--------------------REVIEWS-----------------------*/
.gci-reviews-api-full-box-reviews {
}

/* container for all reviews */
.gci-reviews-api-full-box-reviews-all {
}

.gci-reviews-api-full-box-reviews-all-reviews {
    display: table;
}

.gci-reviews-api-full-box-reviews-all-item {
    display: table-row;
}

.gci-reviews-api-full-box-reviews-all-item > div {
    padding: 20px 10px;
    border-bottom: 1px solid #e3e3e3;
    margin-bottom: 10px;
}

.gci-reviews-api-full-box-reviews-all-item-details {
    display: table-cell;
    width: 200px;
}

.gci-reviews-api-full-box-reviews-all-item-details-name {
    font-size: 16px;
    font-weight: bold;
}

.gci-reviews-api-full-box-reviews-all-item-details-country {
    font-size: 11px;
}

.gci-reviews-api-full-box-reviews-all-item-details-date {
    margin-bottom: 10px;
}

.gci-reviews-api-full-box-reviews-all-item-details-rating {
    margin-bottom: 10px;
}

.gci-reviews-api-full-box-reviews-all-item-details-final-rating {
    font-size: 12px;
}

.gci-reviews-api-full-box-reviews-all-item-text {
    display: table-cell;
    text-align: justify;
}

.gci-reviews-api-full-box-reviews-all-item-text-normal {

}

.gci-reviews-api-full-box-reviews-all-item-text-positive {
}

.gci-reviews-api-full-box-reviews-all-item-text-negative {
}

/*-------------------------- REVIEWS NAVIGATION--------------------------*/
.gci-reviews-api-full-box-reviews-navigation {
    padding: 2px 10px;
    background-color: #F0F0F0;
    clear: both;
    height: 24px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
}

.gci-reviews-api-full-box-reviews-navigation-sort {
}

.gci-reviews-api-full-box-reviews-navigation-links {
    float: right
}

.gci-reviews-api-full-box-reviews-navigation-next {
    padding: 0 10px;
}

.gci-reviews-api-full-box-reviews-navigation-previous {
    padding: 0 10px;
}

.gci-reviews-api-full-box-reviews-navigation-showing {
}

/*-------------------NEW REVIEW FORM----------------*/
.gci-reviews-api-full-box-details-reviews-form {
    display: none;
    padding: 20px;
    border: 1px solid #206083;
    margin: 15px 0px;
    -webkit-border-radius: .5em;
    -moz-border-radius: .5em;
    border-radius: .5em;
}

.gci-reviews-api-full-box-details-reviews-form {
}

.gci-reviews-api-full-box-details-reviews-form-info {
    color: #206083;
    margin: 5px 0;
}

.gci-reviews-api-full-box-details-reviews-form-score {
    display: table;
}

.gci-reviews-api-full-box-details-reviews-form-score-row {
    display: table-row;
    position: relative;
}

.gci-reviews-api-full-box-details-reviews-form-score-label {
    display: table-cell;
    font-weight: bold;
    width: 50%;
    color: #206083;
    padding: 0 20px 5px 0;
}

.gci-reviews-api-full-box-details-reviews-form-score-rating {
    display: table-cell;
    width: 250px;
    padding-bottom: 5px;
}

.gci-reviews-api-full-box-details-reviews-form-text-rating {
}

.gci-reviews-api-full-box-details-reviews-form-text-rating-info {
    font-weight: bold;
    padding: 5px 0;
}

.gci-reviews-api-full-box-details-reviews-form-text-rating-text {
    width: 100%;
    padding: 0;
}

.gci-reviews-api-full-box-details-reviews-form-text-rating-text textarea {
    border: none;
    overflow: auto;
    outline: none;
    padding: 7px 10px;
    margin: 0;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
}

.gci-reviews-api-full-box-details-reviews-form-text-rating-text textarea[name=normal_text] {
    width: 100%;
    height: 75px;
    border: 1px solid #c3c3c3;
}

.gci-reviews-api-full-box-details-reviews-form-text-rating-text-table {
    display: table;
    width: 100%;
}

.gci-reviews-api-full-box-details-reviews-form-text-rating-text-cell {
    width: 50%;
    display: table-cell;
}

.gci-reviews-api-full-box-details-reviews-form-text-rating-text textarea[name=positive_text] {
    width: 100%;
    height: 70px;
    border: 1px solid #c3ffc3;
}

.gci-reviews-api-full-box-details-reviews-form-text-rating-text textarea[name=negative_text] {
    width: 100%;
    height: 70px;
    border: 1px solid #ffc3c3;
}

.gci-reviews-api-full-box-details-reviews-form-text-rating-text textarea:focus {
    border-width: 3px;
    padding: 5px 8px;
}

.gci-reviews-api-full-box-details-reviews-form-contact {
    display: table;
    width: 100%;
    padding-top: 15px;
}

.gci-reviews-api-full-box-details-reviews-form-contact-row {
    display: table-row;
}

.gci-reviews-api-full-box-details-reviews-form-contact-cell {
    display: table-cell;
    width: 50%;
    padding: 2px 5px;
}

.gci-reviews-api-full-box-details-reviews-form-contact-cell input, .gci-reviews-api-full-box-details-reviews-form-contact-cell select {
    padding: 2px 5px;
    width: 200px;
}

.gci-reviews-api-full-box-details-reviews-form-contact-email-info {
    padding: 10px 0;
}

.gci-reviews-api-full-box-details-reviews-form-agree {
    font-weight: normal;
    padding-top: 15px;
}

.gci-reviews-api-full-box-details-reviews-form-send {
}

.gci-reviews-api-full-box-details-reviews-form-send input[type=submit] {
    display: inline-block;
    outline: none;
    cursor: pointer;
    text-align: center;
    text-decoration: none;
    font-weight: bold;
    text-shadow: 0 1px 1px rgba(0, 0, 0, 0.3);
    -webkit-border-radius: .5em;
    -moz-border-radius: .5em;
    border-radius: .5em;
    -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
    -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
    color: #FFFFFF;
    border: solid 1px #da7c0c;
    background: #f78d1d;
    background: -webkit-gradient(linear, left top, left bottom, from(#feba02), to(#f47a20));
    background: -moz-linear-gradient(top, #feba02, #f47a20);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#feba02', endColorstr='#f47a20');

    font-size: 18px;
    padding: 10px 20px;
}

.gci-reviews-api-full-box-details-reviews-form-send input[type=submit]:hover {
    text-decoration: underline;
    background: #f47c20;
    background: -webkit-gradient(linear, left top, left bottom, from(#f88e11), to(#f06015));
    background: -moz-linear-gradient(top, #f88e11, #f06015);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#f88e11', endColorstr='#f06015');
    color: #FFFFFF;
}

.gci-reviews-api-full-box-details-reviews-added {
    background-color: #c3ffc3;
    border: 1px solid #329427;
    color: #329427;
    padding: 10px 15px;
    -webkit-border-radius: .5em;
    -moz-border-radius: .5em;
    border-radius: .5em;
    margin: 10px 0;
    display: none;
}

/**
* Stars
*/
.gci-reviews-rating-medium {
    display: inline-block;
    text-align: left;
    height: 19px;
    width: 105px;
    background: url('<%= image_path 'star_off_medium.png' %>') repeat-x;
}

.gci-reviews-rating-medium span {
    display: inline-block;
    text-align: left;
    height: 19px;
    background: url('<%= image_path 'star_on_medium.png' %>') repeat-x;
}

/**
* Form stars
*/
.gci-reviews-api-full-box-details-reviews-form-score-stars {

}

.gci-reviews-api-full-box-details-reviews-form-score-stars img {
    cursor: pointer;
    border: none;
    padding: 0 2px;
    margin: 0;
}

app/views/gci_reviews/load_reviews.js.erb
// Current shown page
var gciReviews_page = 1;
var gciReviews_sort = 1;
var gci_max_pages = 1; // Will be change by each ajax list request for revies
var thisPageUsingOtherJSLibrary = false;

// Only do anything if jQuery isn't defined
if (typeof jQuery == 'undefined')
{
    if (typeof $ == 'function')
    {
        // warning, global var
        thisPageUsingOtherJSLibrary = true;
    }

    function getScript(url, success)
    {
        var script = document.createElement('script');
        script.src = url;

        var head = document.getElementsByTagName('head')[0],
                done = false;

        // Attach handlers for all browsers
        script.onload = script.onreadystatechange = function ()
        {

            if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete'))
            {
                done = true;
                success();
                script.onload = script.onreadystatechange = null;
                head.removeChild(script);
            }
            ;
        };

        head.appendChild(script);
    };

    getScript('http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js', function ()
    {
        if (typeof jQuery == 'undefined')
        {
            alert('We are sorry, but we could not load main jQuery library to show you reviews. This should not happen. Please contact web administrator.');
        }
        else
        {
            if (thisPageUsingOtherJSLibrary)
            {
                gciReviews_showReviewsBox();
            }
            else
            {
                gciReviews_showReviewsBox();
            }
        }
    });
}
else
{
    gciReviews_showReviewsBox();
};

/**
 * Show reviews full_box - load from GCI page HTML code. All JS should already be loaded
 */
function gciReviews_showReviewsBox()
{
    var $ = jQuery;
    // Load css for styling
    $('head').append($('<link rel="stylesheet" type="text/css" />').attr('href', '<%= gci_reviews_url(api: @gci_reviews_api.api_code, format: :css) %>'));
    $.get('<%= gci_reviews_box_url(api: @gci_reviews_api.api_code) %>', function (data)
    {
        $(".gci-reviews-box").html(data);
    });
}

// Fill Reviews content box with reviews data
function gciReviews_loadReviews()
{
    var $ = jQuery;
    var reviews_template = $("<%= escape_javascript render 'review_tempo' %>");
    var reviews_tempo = Tempo.prepare(reviews_template);
    var reviews_container = $('<div class="gci-reviews-api-full-box-reviews-all">');
    var reviews_box = $(".gci-reviews-api-full-box-reviews");

    navigation = $('<div class="gci-reviews-api-full-box-reviews-navigation">');

    next_page = $('<a href="#" class="gci-reviews-api-full-box-reviews-navigation-next">').html('Next page').click(function (e)
    {
        e.preventDefault();
        if ((gciReviews_page + 1) <= gci_max_pages)
        {
            ++gciReviews_page
            gciReviews_loadReviews();
        }
    });

    previous_page = $('<a href="#" class="gci-reviews-api-full-box-reviews-navigation-previous">').html('Previous page').click(function (e)
    {
        e.preventDefault();
        if ((gciReviews_page - 1) >= 1)
        {
            --gciReviews_page
            gciReviews_loadReviews();
        }
    });

    sortSelect = $('<select>');
    sortSelect.change(function ()
    {
        gciReviews_sort = $(this).val();
        gciReviews_loadReviews();
    });
    sortSelect.append($('<option value="1">').html('Newest first'));
    sortSelect.append($('<option value="2">').html('Oldest first'));
    sortSelect.append($('<option value="3">').html('Most positive first'));
    sortSelect.append($('<option value="4">').html('Most negative first'));

    sort_box = $('<span  class="gci-reviews-api-full-box-reviews-navigation-sort">').append('Sort: ').append(sortSelect);

    $.getJSON('<%= gci_reviews_list_url(api: @gci_reviews_api.api_code) %>?page=' + gciReviews_page + '&sort=' + gciReviews_sort, function (data)
            {
                gci_max_pages = data.count

                reviews_tempo.into(reviews_container).render(data.list);

                // Remove empty texts
                $('.gci-reviews-api-full-box-reviews-all-item-text-normal:empty').remove();
                $('.gci-reviews-api-full-box-reviews-all-item-text-positive:empty').remove();
                $('.gci-reviews-api-full-box-reviews-all-item-text-negative:empty').remove();

                // Update whole reviews box with new content
                showing_info = $('<span class="gci-reviews-api-full-box-reviews-navigation-showing">').html('Showing ' + data.showing_from + ' - ' + data.showing_to);
                navigation_links = $('<div class="gci-reviews-api-full-box-reviews-navigation-links">').append(previous_page).append(showing_info).append(next_page);
                navigation.append(sort_box).append(navigation_links);

                sortSelect.val(gciReviews_sort); // Make sort select to have selected value

                reviews_box.html(reviews_container).prepend(navigation).append(navigation.copy);
            }
    );
}


function gciReviews_formStars()
{
    $(".gci-reviews-api-full-box-details-reviews-form-score-stars img").hover(function ()
    {
        $(this).prevAll().attr('src', '<%= image_url 'star_on_medium.png' %>');
        $(this).attr('src', '<%= image_url 'star_on_medium.png' %>');
        $(this).nextAll().attr('src', '<%= image_url 'star_off_medium.png' %>');

    }, function ()
    {
        var score = $(this).parent().find('input').val();

        if (score == -1 || score == 0)
            $(this).parent().find('img').attr('src', '<%= image_url 'star_off_medium.png' %>');
        else
        {
            score++;
            $(this).parent().find('img:nth-child(' + score + ')').prevAll().attr('src', '<%= image_url 'star_on_medium.png' %>');
            $(this).parent().find('img:nth-child(' + score + ')').nextAll().attr('src', '<%= image_url 'star_off_medium.png' %>');
            $(this).parent().find('img:nth-child(' + score + ')').attr('src', '<%= image_url 'star_on_medium.png' %>');
        }
    });

    $(".gci-reviews-api-full-box-details-reviews-form-score-stars img").click(function ()
    {
        var input = $(this).parent().find('input');
        var score = $(this).parent().find('img').index(this) + 1;
        input.val(score);
    });
}

function gciReviews_formSubmit()
{
    var reviewsForm = $(".gci-reviews-api-full-box-details-reviews-form");

    $("#gci-reviews-form").submit(function (e)
    {
        e.preventDefault();

        // Disable form (prevent double submission)
        $("#gci-reviews-form :input").attr('readonly', true);

        var formData = $(this).serialize();
        $.ajax({
            type: "POST",
            url: '<%= gci_reviews_new_url(api: @gci_reviews_api.api_code) %>',
            data: formData,
            success: function (data)
            {
                // Enable form
                $("#gci-reviews-form :input").removeAttr('readonly');

                if (data.status == 'ok')
                {
                    reviewsForm.slideUp();

                    // Clean form
                    $('#gci-reviews-form :input').not(':button, :submit, :reset, :hidden').val('').removeAttr('checked').removeAttr('selected');

                    // Show message
                    $(".gci-reviews-api-full-box-details-reviews-added ").slideDown(function ()
                    {
                        // Hide after 5 seconds
                        setTimeout(function ()
                        {
                            $(".gci-reviews-api-full-box-details-reviews-added ").slideUp();
                        }, 5000);
                    });

                    // Scroll to message
                    gciReviews_scrollTo(".gci-reviews-api-full-box-details-reviews-added");
                }
            }
        });
    });
}

function gciReviews_scrollTo(element)
{
    $('html, body').animate({
        scrollTop: $(element).offset().top - 70
    }, 700);
}

<%= render 'tempo' %>