config/routes.rb
GCIReviews::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :account do
    resources :gci_reviews_apis
    resources :gci_reviews_api_color_schemes
  end

  root 'static_pages#index'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'sign-in' => 'session#new', as: 'sign_in'
  post 'sign-in' => 'session#create', as: 'sign_in_create'
  delete 'sign-out' => 'session#destroy', as: 'sign_out'
  get 'sign-up' => 'static_pages#sign_up', as: 'sign_up'
  post 'sign-up' => 'static_pages#sign_up_create', as: 'sign_up_create'

  get 'account' => 'session#index'

  get 'reviews/:api' => 'gci_reviews#load', :defaults => { :format => :js }, as: 'gci_reviews'
  get 'reviews/:api/box' => 'gci_reviews#box', :defaults => { :format => :html }, as: 'gci_reviews_box'
  get 'reviews/:api/list' => 'gci_reviews#list', :defaults => { :format => :json }, as: 'gci_reviews_list'
  post 'reviews/:api/new' => 'gci_reviews#new', :defaults => { :format => :json }, as: 'gci_reviews_new'
  match 'reviews/:api/new', to: 'gci_reviews#set_options', via: :options

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GCI Reviews", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <%= nav_links %>

      <% if !online? %>
          <div class="navbar-form navbar-right">
            <%= link_to "Sign in", sign_in_path, class: "btn btn-success" %>
            <%= link_to "Sign up", sign_up_path, class: "btn btn-primary" %>
          </div>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.full_name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", account_path %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", sign_out_path, method: "delete" %>
                </li>
              </ul>
            </li>
          </ul>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= full_title yield(:title) %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |key, value| %>
        <% if key == :notice then
             key = :info
           end %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>

    <hr>

    <footer>
      <p>&copy; MedBeaver.com 2014</p>
    </footer>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>